//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RBACEntities : DbContext
    {
        public RBACEntities()
            : base("name=RBACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sys_Buttons> Sys_Buttons { get; set; }
        public virtual DbSet<Sys_Departments> Sys_Departments { get; set; }
        public virtual DbSet<Sys_Groups> Sys_Groups { get; set; }
        public virtual DbSet<Sys_LogDetails> Sys_LogDetails { get; set; }
        public virtual DbSet<Sys_Logs> Sys_Logs { get; set; }
        public virtual DbSet<Sys_LogSettings> Sys_LogSettings { get; set; }
        public virtual DbSet<Sys_Navigations> Sys_Navigations { get; set; }
        public virtual DbSet<Sys_Roles> Sys_Roles { get; set; }
        public virtual DbSet<Sys_Users> Sys_Users { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Sys_Users_Groups> Sys_Users_Groups { get; set; }
        public virtual DbSet<Sys_GroupNavBtns> Sys_GroupNavBtns { get; set; }
        public virtual DbSet<Sys_Users_Departments> Sys_Users_Departments { get; set; }
        public virtual DbSet<Sys_UserNavBtns> Sys_UserNavBtns { get; set; }
        public virtual DbSet<Sys_Roles_Departments> Sys_Roles_Departments { get; set; }
        public virtual DbSet<Sys_RoleNavBtns> Sys_RoleNavBtns { get; set; }
        public virtual DbSet<Sys_NavButtons> Sys_NavButtons { get; set; }
        public virtual DbSet<Sys_Users_Roles> Sys_Users_Roles { get; set; }
        public virtual DbSet<Sys_Parameter> Sys_Parameter { get; set; }
    }
}
