//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Buttons
    {
        public Sys_Buttons()
        {
            this.Sys_GroupNavBtns = new HashSet<Sys_GroupNavBtns>();
            this.Sys_UserNavBtns = new HashSet<Sys_UserNavBtns>();
            this.Sys_RoleNavBtns = new HashSet<Sys_RoleNavBtns>();
            this.Sys_NavButtons = new HashSet<Sys_NavButtons>();
            this.AddTime = DateTime.Now;
        }
    
        public int Id { get; set; }
        public string ButtonText { get; set; }
        public int SortNum { get; set; }
        public string IconCls { get; set; }
        public string IconUrl { get; set; }
        public string ButtonTag { get; set; }
        public string ButtonHtml { get; set; }
        public string Remark { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual ICollection<Sys_GroupNavBtns> Sys_GroupNavBtns { get; set; }
        public virtual ICollection<Sys_UserNavBtns> Sys_UserNavBtns { get; set; }
        public virtual ICollection<Sys_RoleNavBtns> Sys_RoleNavBtns { get; set; }
        public virtual ICollection<Sys_NavButtons> Sys_NavButtons { get; set; }
    }
}
