//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Roles_Departments
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int DepId { get; set; }
        public string Remark { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual Sys_Departments Sys_Departments { get; set; }
        public virtual Sys_Roles Sys_Roles { get; set; }
    }
}
