//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users
    {
        public Sys_Users()
        {
            this.Sys_Logs = new HashSet<Sys_Logs>();
            this.Sys_Users_Groups = new HashSet<Sys_Users_Groups>();
            this.Sys_Users_Departments = new HashSet<Sys_Users_Departments>();
            this.Sys_UserNavBtns = new HashSet<Sys_UserNavBtns>();
            this.Sys_Users_Roles = new HashSet<Sys_Users_Roles>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string PassSalt { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public string TrueName { get; set; }
        public string Mobile { get; set; }
        public string QQ { get; set; }
        public string MenusJson { get; set; }
        public string ConfigJson { get; set; }
        public string Remark { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual ICollection<Sys_Logs> Sys_Logs { get; set; }
        public virtual ICollection<Sys_Users_Groups> Sys_Users_Groups { get; set; }
        public virtual ICollection<Sys_Users_Departments> Sys_Users_Departments { get; set; }
        public virtual ICollection<Sys_UserNavBtns> Sys_UserNavBtns { get; set; }
        public virtual ICollection<Sys_Users_Roles> Sys_Users_Roles { get; set; }
    }
}
