//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Groups
    {
        public Sys_Groups()
        {
            this.Sys_Users_Groups = new HashSet<Sys_Users_Groups>();
            this.Sys_GroupNavBtns = new HashSet<Sys_GroupNavBtns>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Remark { get; set; }
        public int ParentId { get; set; }
    
        public virtual ICollection<Sys_Users_Groups> Sys_Users_Groups { get; set; }
        public virtual ICollection<Sys_GroupNavBtns> Sys_GroupNavBtns { get; set; }
    }
}
