//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_LogSettings
    {
        public Sys_LogSettings()
        {
            this.Sys_Logs = new HashSet<Sys_Logs>();
        }
    
        public int Id { get; set; }
        public string TableName { get; set; }
        public string BusinessName { get; set; }
        public string PrimaryKey { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Sys_Logs> Sys_Logs { get; set; }
    }
}
