//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Logs
    {
        public Sys_Logs()
        {
            this.Sys_LogDetails = new HashSet<Sys_LogDetails>();
        }
    
        public int Id { get; set; }
        public int LogSettingId { get; set; }
        public int UserId { get; set; }
        public string PrimaryKeyValue { get; set; }
        public string OperationIP { get; set; }
        public string SqlText { get; set; }
        public string Url { get; set; }
        public System.DateTime AddTime { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Sys_LogDetails> Sys_LogDetails { get; set; }
        public virtual Sys_LogSettings Sys_LogSettings { get; set; }
        public virtual Sys_Users Sys_Users { get; set; }
    }
}
